name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Unit test
        uses: kohidave/proton-jinja-template-validation-action
      - name: RunUnitTests
        run: |
          python -m unittest 
